### ISSUE TITLE
ingress with tcp forwarding capabilities 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-sdk#1936]
Right now the ingress used is traefik 1.7 or 1.8, which doesn't have the features for tcp forwarding. the tcp forwarding feature is required for threefoldtech/vdc-solutions-charts#13, suggested solution is upgrading to traefik 2.2 in k3os image

**Comment by OmarElawady** [comment]
The entrypoint in the sample is changed to 'websecure'.
To update traefik version to 2.3.3, I changed the content of `/var/lib/rancher/k3s/server/manifests/traefik.yaml` as described [here](https://rancher.com/docs/k3s/latest/en/networking/) to:
```
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: traefik
  repo: https://helm.traefik.io/traefik
  set:
    image.tag: "2.3.3"
    ports.websecure.tls.enabled: true
```
And the new version got automatically installed. I tested peertube, mattermost, and the sample in the comment and they all worked. The address in the ingress is empty but it seems that nothing is broken.

it currently generates a self signed certificate will see how to use a CA instead.
